### ISSUE TITLE
Highlight matches for templates?

### ISSUE THREAD

**Issue by kayleiburke** [matfish2/vue-tables-2#389] opened 2018-01-11 16:39 UTC
- **Vue.js version:**  2.5.9
- **consumed using:** Webpack
- **FULL error message (including stack trace):**  None
- **relevant code:**
```
<v-server-table url="/my_api_url.json" v-on:filter="onFilter" v-on:row-click="onRowClick" :columns="columns" :options="options" ref="vuetable">
      <template slot="user.description" slot-scope="props">
        {{props.row.user.description}}
      </template>
</v-server-table>
...
...
data: function () {
      return {
        columns: [ 'id', 'description', 'user.description' ],
        options: {
          sortable: ['id', 'description', 'user.description'],
          highlightMatches: true,
...
       }
     }
}
```
-  First of all, thank you very much for your hard work on this table!  The functionality and documentation is spectacular!  I love the highlightMatches feature of this table.  However, I'm having a hard time highlighting matches for my templates created using scoped slots.  When I perform a search, the results are properly filtered, but only matches in my non-templated columns are highlighted.  Is there a way I can adjust my configuration or change my code to fix this issue?

**Comment by matfish2** [comment] 2018-01-11 21:24
Duplicate of #253

**Closed by matfish2** 2018-01-11 21:24 UTC
Labels: duplicate
