### ISSUE TITLE
EloquentVueTables.php logic error: $orderBy always truthy because it is a string

### ISSUE THREAD

**Issue by mcnamarabryan** [matfish2/vue-tables-2#324] opened 2017-11-03 01:34 UTC
- Vue.js version: 2.4.4
- consumed using: (browserify/webpack/rollup) webpack
- FULL error message (including stack trace): 

> Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'false' in 'order clause' (SQL: select `guid`, `vendor`, `name`, `url`, `sku`, `price_string`, `description_short`, `description_long`, `images`, `categories` from `productscrapes` order by `false` asc limit 10 offset 0) in /home/vagrant/code/ptu2spark/vendor/laravel/framework/src/Illuminate/Database/Connection.php:647

- relevant code: EloquentVueTables.php : Line 37
- steps for reproducing the issue: Using vue-tables-2 version 0.6.85 and EloquentVueTables.php, load a table. Load fails because $orderBy == 'false', which is true in PHP because it is truthy that it is a string.

Fix: Change logic in line 37 to:
`if (isset($orderBy) && $orderBy != 'false'):`

**Comment by matfish2** [comment] 2017-11-03 08:37
Duplicate of #320

**Closed by matfish2** 2017-11-03 08:37 UTC
Labels: duplicate
