### ISSUE TITLE
Custom columnsDropdown

### ISSUE THREAD

**Issue by fasterlars** [matfish2/vue-tables-2#695] opened 2019-04-21 13:14 UTC
I would like to create my own columnsdropdown. As far as I can see, there is no slot option like there is with childRow. 
As seen in this example https://jsfiddle.net/jfa5t4sm/2601/ - it is possible to hide the limit selector, and then create your own which calls a setLimit method on the table. But I cant see any method related to the column choosing in the docs. 
So is it even possible to create your own styled columns dropdown?
Thanks!

**Comment by AyushiBShah** [comment] 2019-07-13 10:21
Any luck on this ?

**Comment by alexander-wecode** [comment] 2019-09-26 16:48
A bit of a haxy one, but it works for me.
My uuid/field.uuid is the column name, change it out with yours.

HTML
`
<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <div class="dropdown-item"
                                   v-for="field in fields"
                                   @click="toogleFieldVisibility(field.uuid)"
                                >
                                    <input type="checkbox" :checked="fieldIsVisible(field.uuid) ? 'checked' : ''" class="d-inline">
                                    <div class="t-head-col d-inline px-2">
                                        {{field.name)}}
                                    </div>
                                </div>
                            </div>

<v-server-table ref="table" :columns="columns" :options="options" :name="name" >

`

Access the child table methods directly by using its ref.
Methods:
`
fieldIsVisible(uuid){
   const columnsDisplay = this.$refs.table.userColumnsDisplay;
   return columnsDisplay.includes(uuid);
 },
toogleFieldVisibility(uuid){
   this.$refs.table.toggleColumn(uuid);
},
`

**Comment by matfish2** [comment] 2019-10-24 21:49
That's more a templating issue. The plugin does offer custom templates option, but ATM it is somewhat cumbersome. I hope to offer a more granular solution in the near future.

**Comment by matfish2** [comment] 2019-10-31 17:29
closing as a duplicate of the more generic #738

**Closed by matfish2** 2019-10-31 17:29 UTC
Labels: feature request
