### ISSUE TITLE
highlightMatches doesn't apply to data output using a <template> 

### ISSUE THREAD

**Issue by techytuppers** [matfish2/vue-tables-2#340] opened 2017-11-28 12:38 UTC
- Vue.js version: 2.4.4
- consumed using: webpack
- FULL error message (including stack trace): N/A

Using a template for column data e.g.

```
<v-client-table ref="portfolioTable" id="portfolio" :data="portfolioItems" :columns="columns" :options="options">
<!-- Template for Market Price -->
<template slot="MarketPrice" slot-scope="props">
     {{ props.row.MarketPrice | currency('£') }}
</template>
</v-client-table>
```
with option `highlightMatches` set to `true`

Any data in a template like above, doesn't get treated the same with highlight as data that is output in it's native manner. **Even removing the filter**, so it outputs the data as it would without the template, doesn't show the highlight functionality.

Any advice on how to incorporate the highlight functionality to customised template views?

Thanks! TT

**Comment by matfish2** [comment] 2017-11-28 12:40
Duplicate of #253

**Closed by matfish2** 2017-11-28 12:40 UTC
Labels: duplicate

**Comment by techytuppers** [comment] 2017-11-28 12:42
Ah, apologies!
