### ISSUE TITLE
Vue-tables-2 will only trigger one event when using existing Vuex module.

### ISSUE THREAD

**Issue by rSammy** [matfish2/vue-tables-2#541] opened 2018-06-08 14:53 UTC
**- Vue.js version**: Latest
**- consumed using**: (webpack)
**- FULL error message** (including stack trace):
Vue warn]: Error in render: "TypeError: _this.allColumns is undefined"

found in

---> <ServerTable>

**I thought I had to create some module to use it with vuex.
I created one I called users.js**

Whenever I use it with existing Vuex .js file, it only fires one event. 
If I try to paginate, **only the paginate event** will get fired and will only trigger the paginate mutation that's the same for filter and **all of the events**.
 
Since we can't trigger actions from Vuex mutation it's pretty useless.

When I use some **non existing vuex store module**, all of the events triggers fine...

```
import axios from 'axios';

const users = {
    state: {
        ascending:true,
        columns : ['check','id', 'uuid', 'country', 'email', 'username'],
        count : 0,
        customQueries : {},
        data : [],
        limit : 10,
        page : 1,
        query : "",
        sortBy: false
    },

// getters
    getters: {

    },

// actions
    actions: {

    },

// mutations
    mutations: {
        ['users/LOADED'](state, data) {
            state.data = data.data.data;
            state.count = data.data.count;
        },
        ['users/FILTER'](state, data) {
            // Do something
        },
        ['users/SORTED'](state, data) {
            // Do something
        },
        ['users/LOADING'](state, data) {
            // Do something
            state.ascending = data.ascending;
            state.byColumn = data.byColumn;
            state.limit = data.limit;
            state.page = data.page;
            state.query = data.query;
        },
        ['users/PAGINATE'](state, data) {
            
        },
        ['users/LIMIT'](state, data) {
            // Do something
        },
        ['users/ERROR'](state, data) {
            // Do something
        },
        ['users/ROW_CLICK'](state, data) {
            // Do something
            console.log(data);
        },
        ['users/SET_DATA'](state, data) {

        },
    }
};
export default users;
```
`<v-server-table :class="{loading:isLoading}" @loading="toggleClass" @loaded="toggleClass" name="users" :url="user_route" :columns="columns" :options="options">`

```
import Vue from 'vue'
import Vuex from 'vuex'
import chat from './modules/chat'
import users from './modules/users'

Vue.use(Vuex);

const debug = true;

export default new Vuex.Store({
    modules: {
        chat,
        users
    },
});
```

**How can I use vuex ?**
Pagination doesn't work, I need to specify manually columns... I don't understand how does it works at all

**Comment by matfish2** [comment] 2018-06-08 18:59
Duplicate of #505

**Closed by matfish2** 2018-06-08 18:59 UTC
