### ISSUE TITLE
Can't get the datefilter to work

### ISSUE THREAD

**Issue by Tjitse-E** [matfish2/vue-tables-2#402] opened 2018-01-22 09:53 UTC
Hi,

I've tried setting up a Vue component with Vue-tables-2. The goal is to get a working datepicker. I've setup the following example to test this (source: https://medium.com/@lopezquekk/how-to-use-vue-tables-2-tables-for-vuejs-c56b7823c9c2).

I've managed to get everything, except the datepicker working. The rest of the filters (years in school, student name) are working correctly. The datepicker is visible, but when I choose one of the values, nothing is returned.

MomentJS is working as expected, i've tested this with `console.log(moment("2004-05-19"));`

Any ideas what i'm doing wrong?

- Vue.js version: 
```
    "axios": "^0.15.3",
    "bootstrap": "^3.0.0",
    "cross-env": "^3.2.3",
    "daterangepicker": "^2.1.27",
    "gulp": "^3.9.1",
    "jquery": "^2.1.4",
    "js-cookie": "^2.1.0",
    "laravel-mix": "0.*",
    "moment": "^2.20.1",
    "promise": "^7.1.1",
    "sweetalert": "^1.1.3",
    "underscore": "^1.8.3",
    "urijs": "^1.17.0",
    "vue": "2.*",
    "vue-good-table": "^1.19.1",
    "vue-tables-2": "^1.2.44"
```

- consumed using: (browserify/webpack/rollup) - webpack
- FULL error message (including stack trace): - none
- relevant code:
```
<template>
    <v-client-table :data="rows" :columns="columns" :options="options"></v-client-table>
</template>

<script>
    import axios from 'axios';
    import daterangepicker from 'daterangepicker';

    //This is very important to used with the window object
    window.moment = require('moment');

    console.log(moment("2004-05-19"));

    export default {
        data(){
            return{
                columns: [ 'id', 'name','birth','year','number'],
                options: {
                    filterByColumn: true,
                    perPage:10,
                    texts: {
                        filter: "Filtrar:",
                        filterBy: 'Filtrar por {column}',
                        count:' '
                    },
                    dateColumns:['birth'],
                    dateFormat: 'YYYY-MM-DD',
                    datepickerOptions: {
                        showDropdowns: true,
                        autoUpdateInput: true,
                    },
                    pagination: { chunk:10,dropdown:false },
                    filterable:['name','birth','year'],
                    headings: {
                        name: 'Student Name',
                        year: 'Year in School',
                        number: 'Number ID',
                        id: 'ID',
                    },
                },
                rows:[
                    {id:1, name:"John",birth:moment("2004-05-19"), year:"5", number:"17"},
                    {id:2, name:"Jane",birth:moment("2004-05-19"), year:"6", number:"18"},
                    {id:3, name:"Susan",birth:moment("2004-05-19"), year:"7", number:"19"},
                    {id:4, name:"Chris",birth:moment("2004-05-19"), year:"8", number:"20"},
                    {id:5, name:"Dan",birth:moment("2004-05-19"), year:"9", number:"21"}
                ],
            }

        }

    };

</script>
```

Steps for reproducing the issue:
- Add component
- Select date filter: 2003-01-01 - 2006-02-01
- No data is returned

**Comment by matfish2** [comment] 2018-01-22 09:57
Duplicate of #401 
Download latest version

**Closed by matfish2** 2018-01-22 09:57 UTC
Labels: duplicate
