### ISSUE TITLE
Minified js version 

### ISSUE THREAD

**Issue by Diaskhan** [matfish2/vue-tables-2#157] opened 2017-05-12 08:55 UTC
It is posssible to use table library without Webpack bunlder.

Just include as 
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

An use it ???

**Comment by matfish2** [comment] 2017-05-14 12:20
Duplicate of #123

**Closed by matfish2** 2017-05-14 12:20 UTC
