### ISSUE TITLE
orderBy is not thrown in AJAX request

### ISSUE THREAD

**Issue by singiankay** [matfish2/vue-tables-2#382] opened 2018-01-05 07:16 UTC
I updated from version 0.6.69 to 1.2.40. 

Now my server-table doesn't add the orderBy query string parameter.

These are the params being added to the request: limit, ascending, page, byColumn.

I can't find the fix to this in the documentation.

How can I set the orderBy to the AJAX request?

**Comment by matfish2** [comment] 2018-01-05 19:02
Duplicate of #320

**Closed by matfish2** 2018-01-05 19:02 UTC
Labels: duplicate
