### ISSUE TITLE
where is the 'dist' folder?

### ISSUE THREAD

**Issue by sncer** [matfish2/vue-tables-2#150] opened 2017-05-07 15:34 UTC
In the vue-tables, there is a compiled standalone file in its dist folder. But I can't find such file to import into my HTML, which is convenient to use this package. So, can you add this compiled standalone file in present package?

**Comment by matfish2** [comment] 2017-05-08 05:32
Duplicate of #123

**Closed by matfish2** 2017-05-08 05:32 UTC
Labels: duplicate
