### ISSUE TITLE
Question: how to disable initial sorting?

### ISSUE THREAD

**Issue by andreesteve** [matfish2/vue-tables-2#210] opened 2017-07-10 04:55 UTC
Is it possible to disable the initial order by on the client table? I would like to present the table rows in the same order as in the data array.

I tried setting ```orderBy.column``` to falsy, but it defaults to the first column.

**Comment by matfish2** [comment] 2017-07-13 20:53
Duplicate of #193.

`orderBy:{column:false}` works for me. Did you download the most recent version?

**Closed** 2017-07-16 19:53 UTC
Labels: duplicate
