### ISSUE TITLE
v-server-table attempting to generate table before getting data from server

### ISSUE THREAD

**Issue by jasonlfunk** [matfish2/vue-tables-2#200] opened 2017-06-26 11:59 UTC
This is reopening bug #166. This is definitely happening.

- Vue.js version: 2.1.10
- consumed using: webpack
- FULL error message (including stack trace):

```
dist.min.js:31 TypeError: Cannot read property 'map' of undefined
    at Array.concat.module.exports (1.js:6244)
    at a.<anonymous> (1.js:1807)
    at a.e._render (dist.min.js:32)
    at a.r (dist.min.js:31)
    at So.get (dist.min.js:32)
    at new So (dist.min.js:32)
    at ve (dist.min.js:31)
    at a.pt.$mount (dist.min.js:33)
    at a.pt.$mount (dist.min.js:33)
    at init (dist.min.js:32)
```
The stack trace comes from `compiled/template.js` where its `var rows = require('./template/rows')(h, this)`. This seems to then try to map the data property from here: 
```
    var data = that.source == 'client' ? that.filteredData : that.tableData;
    data.map(function (row, index) {
```

This is failing because `that.tableData` is undefined. My server is returning the correct data, it just doesn't have it yet. The table does render, but sorting/etc doesn't work because of the javascript error.

If I manually wrap the `map` with a check to make sure data is an array, everything works fine. However, that's not probably the best solution.

**Comment by matfish2** [comment] 2017-06-26 14:34
Can you paste the response you get from the server?
Also, are you using `vuex` or not? 

`tableData` is a computed property that simply returns that `data` property, which is initialized as an empty array. AFAIK, The only place in the code where `data` is reassigned is after a response from the server.

**Comment by jasonlfunk** [comment] 2017-06-26 15:17
It's fake data, but it looks like this:

```
{"data":[{"checkbox":false,"id":"1940-B","customer":"John Doe","company":"--","date":"Jun 0, 2017","status":"Pending","payment":"Captured","total":"$50.99","verified":true,"collapse":true,"actions":""},{"checkbox":false,"id":"1941-B","customer":"John Doe","company":"--","date":"Jun 1, 2017","status":"Pending","payment":"Captured","total":"$51.99","verified":true,"collapse":true,"actions":""},{"checkbox":false,"id":"1942-B","customer":"John Doe","company":"--","date":"Jun 2, 2017","status":"Pending","payment":"Captured","total":"$52.99","verified":true,"collapse":true,"actions":""},{"checkbox":false,"id":"1943-B","customer":"John Doe","company":"--","date":"Jun 3, 2017","status":"Pending","payment":"Captured","total":"$53.99","verified":true,"collapse":true,"actions":""},{"checkbox":false,"id":"1944-B","customer":"John Doe","company":"--","date":"Jun 4, 2017","status":"Pending","payment":"Captured","total":"$54.99","verified":true,"collapse":true,"actions":""},{"checkbox":false,"id":"1945-B","customer":"John Doe","company":"--","date":"Jun 5, 2017","status":"Pending","payment":"Captured","total":"$55.99","verified":true,"collapse":true,"actions":""},{"checkbox":false,"id":"1946-B","customer":"John Doe","company":"--","date":"Jun 6, 2017","status":"Pending","payment":"Captured","total":"$56.99","verified":true,"collapse":true,"actions":""},{"checkbox":false,"id":"1947-B","customer":"John Doe","company":"--","date":"Jun 7, 2017","status":"Pending","payment":"Captured","total":"$57.99","verified":true,"collapse":true,"actions":""},{"checkbox":false,"id":"1948-B","customer":"John Doe","company":"--","date":"Jun 8, 2017","status":"Pending","payment":"Captured","total":"$58.99","verified":true,"collapse":true,"actions":""},{"checkbox":false,"id":"1949-B","customer":"John Doe","company":"--","date":"Jun 9, 2017","status":"Pending","payment":"Captured","total":"$59.99","verified":true,"collapse":true,"actions":""}],"count":100}
```

**Comment by jasonlfunk** [comment] 2017-06-26 15:19
And the code (stripped down) looks like:

```
<template>
  <div id="orders">
    <v-server-table
      ref="orders"
      :url="tblUrl"
      :columns="columns"
      :options="options"
    ></v-server-table>
  </div>
</template>

<script>
  import { ServerTable } from 'vue-tables-2';
  Vue.use(ServerTable);

  export default {
    name: 'Orders',
    data() {
      let self = this;
      return {
        tblUrl: [removed],
        columns: ['checkbox', 'id', 'customer', 'company', 'date', 'status', 'payment', 'total', 'verified', 'collapse', 'actions'],
        options: {
          skin: '',
          filterable: false,
          headings: {
            checkbox(h) {
              return <input type='checkbox' />;
            },
            collapse: '',
            actions: '',
          },
          childRow: function(h, row) {
            return [removed];
          },
          rowClassCallback(row) {
            return row.collapse ? '' : 'open'
          },
          templates: {
            checkbox(h, row) {
              return <input type='checkbox' checked={row.checkbox} />;
            },
            verified(h, row) {
              return <div>{row.verified ? 'Verified' : 'Unverified'}</div>;
            },
            collapse(h, row) {
              return <a href='#' onClick={($event)=>{ self.toggleRow(row, $event); }}>
                {row.collapse ? 'Show More ▼' : 'Show Less ▲'}
              </a>;
            },
            actions(h, row) {
              return <div>⋅⋅⋅</div>
            }
          },
        },
      };
    }
  };
</script>
```

**Comment by matfish2** [comment] 2017-06-26 15:33
Seems fine. What ajax plugin are you using? (JQuery, axios or vue-resource)

**Comment by alfiehub** [comment] 2017-06-26 18:22
I think I'm experiencing the same problem using these versions

```
"vue": "^2.3.4"
"vue-resource": "^1.3.4",
"vue-tables-2": "^0.6.37",
```

```
Uncaught (in promise) TypeError: Cannot read property 'map' of undefined
    at VueComponent.module.exports (apply-filters.js?c856:4)
    at VueComponent.boundFn [as applyFilters] (vue.js?e1b2:170)
    at VueComponent.module.exports (set-data.js?1d48:4)
    at VueComponent.boundFn [as setData] (vue.js?e1b2:170)
    at VueComponent.eval (v-server-table.js?44f6:82)
    at <anonymous>
```

**Comment by matfish2** [comment] 2017-06-26 18:48
I'm using the exact same versions. Unable to reproduce.
Can you `console.log(data)` in `set-data.js` and paste the first result on page load?

**Comment by jasonlfunk** [comment] 2017-06-27 09:51
The error is happening before set data is called.

<img width="631" alt="screen shot 2017-06-27 at 4 50 12 pm" src="https://user-images.githubusercontent.com/685188/27581750-beba8f00-5b58-11e7-8382-1edee3b7c0bd.png">

**Comment by matfish2** [comment] 2017-06-27 13:43
Can you click on the first line in the stack trace, so I can see which line is causing the error?

**Comment by jasonlfunk** [comment] 2017-06-28 00:51
I included it in the original issue.  :)

**Comment by jasonlfunk** [comment] 2017-06-29 06:42
By the way, I just switched my code from using a global vue and jQuery) (installed on the window object) to importing vue and axios locally in the component and the problem went away. I'm not sure how to explain that. :)

**Comment by matfish2** [comment] 2017-07-01 09:56
I am inclined to think that it's not the change of scope that did the trick, but rather using a different ajax library (axios instead of JQuery). I tested the package with all three supported options (axios, JQuery and vue-resource), but maybe it's a matter of version. With that in mind what version of JQuery were you using?

**Comment by jasonlfunk** [comment] 2017-07-03 05:01
I switched from axios to jQuery and the problem didn't come back. I was using jQuery 3.1.1.

**Comment by jasonlfunk** [comment] 2017-07-03 05:03
Have you tested it with a global Vue and global jQuery?

**Comment by matfish2** [comment] 2017-07-04 16:53
JQuery **must** be global, as does axios, in case you are using it, otherwise the package has no access to it.  
As for Vue, I fail to see how it could be the source, but yes, I have tested it with global Vue as well.

**Closed by matfish2** 2017-07-04 16:53 UTC

**Comment by saaiful** [comment] 2017-07-16 18:34
I'm using my vue app with electron and getting following error:
`Uncaught (in promise) TypeError: data.map is not a function
    at VueComponent.module.exports (app.js:42428)
    at VueComponent.boundFn [as applyFilters] (app.js:11938)
    at VueComponent.module.exports (app.js:43057)
    at VueComponent.boundFn [as setData] (app.js:11938)
    at VueComponent.<anonymous> (app.js:44366)`

My bootstarp.js file includes jquery and axios 
`window.$ = window.jQuery = require('jquery');
window.axios = require('axios');`

**Comment by matfish2** [comment] 2017-07-16 19:20
Can you `console.log(response)` in get-data.js:27 and paste the result?

**Comment by saaiful** [comment] 2017-07-16 19:30
```
var data = this.getResponseData(response);
    console.log(response);
    return this.setData(this.opts.responseAdapter(data));
```

Same Error Uncaught (in promise) TypeError: data.map is not a function
    at VueComponent.module.exports (app.js:42455)
    at VueComponent.boundFn [as applyFilters] (app.js:11938)
    at VueComponent.module.exports (app.js:43084)
    at VueComponent.boundFn [as setData] (app.js:11938)
    at VueComponent.<anonymous> (app.js:44393)

**Comment by matfish2** [comment] 2017-07-16 19:31
Actually the first response is set in `v-server-table.js`. Please add the log in line 80.

**Comment by saaiful** [comment] 2017-07-16 19:36
response
:
"{"data":{"id":1,"barcode":"10000007","name":"Item 1","details":"","purchase":100,"sale":150,"min_sale":130,"manage_stock":1,"stock":10,"created_at":"2017-07-16 22:55:00","has_warranty":0,"warranty_days":0},"count":1}"
responseText
:
"{"data":{"id":1,"barcode":"10000007","name":"Item 1","details":"","purchase":100,"sale":150,"min_sale":130,"manage_stock":1,"stock":10,"created_at":"2017-07-16 22:55:00","has_warranty":0,"warranty_days":0},"count":1}"
responseType
:
""

**Comment by matfish2** [comment] 2017-07-16 19:42
I meant `console.log(response.data)`, not `data`. I suspect it might return as a string rather than an array of objects.

**Comment by saaiful** [comment] 2017-07-16 19:46
It returns object not string

**Comment by matfish2** [comment] 2017-07-16 19:47
This is the response I'm getting from `axios`
![screenshot at jul 16 22-45-40](https://user-images.githubusercontent.com/1510460/28250735-a1f498f0-6a78-11e7-9dab-0c25e201b234.png)
Please make sure you have the same data structure

**Comment by saaiful** [comment] 2017-07-16 19:48
http://picgi.com/w7ydfgc it's my response data:[] and count int

**Comment by matfish2** [comment] 2017-07-16 19:49
is it your original `response` or `response.data`?

**Comment by saaiful** [comment] 2017-07-16 19:53
My server response was wrong, Just fixed it, Thanks a lot
