### ISSUE TITLE
columnsDisplay - doesn't hide columns on page load

### ISSUE THREAD

**Issue by webdevnerdstuff** [matfish2/vue-tables-2#453] opened 2018-03-07 22:09 UTC
- Vue.js version: 2.4.1
- vue-tables-2 version: 1.0.0 & 1.3.61
- consumed using: webpack
- FULL error message (including stack trace): n/a

- description
On first page load, columnsDisplay does not always work. I noticed a few times that on first page load all columns were there, but on orientation change, they worked as intended. I first tried this on v 1.0.0. thinking "min_" wasn't working, but then ran into the same problem on 1.3.61.

- steps
1. Add columnsDisplay with the preferred values
2. Load the page on mobile/tablet/desktop/whatever
3. Notice that all columns are displayed even when set to "not"
4. Change page orientation
5. Notice the columns set to not display, are not there anymore and it works as intended.

**Comment by matfish2** [comment] 2018-03-14 20:04
I wasn't able to reproduce. The `windowWidth` property is set initially to `window.innerWidth`. This value is then reassigned when the window is resized. Can you whip up a fiddle that demonstrates the problem?

**Comment by webdevnerdstuff** [comment] 2018-03-14 23:43
Ignore all the other files except for Stats.vue. Also ignore the browser since this is just a simple example.

https://codesandbox.io/s/xz7qo4n9o

**Comment by matfish2** [comment] 2018-03-15 00:05
The example doesn't work. After modifying it I managed to load the table heading. Only columns 3 to 5 are presented, as expected (columns 1 and 2 two are defined as `mobile`).
https://codesandbox.io/s/104vzj9m67

**Comment by matfish2** [comment] 2018-04-28 15:35
Closing due to inactivity

**Closed by matfish2** 2018-04-28 15:35 UTC
