### ISSUE TITLE
Add specific column classes

### ISSUE THREAD

**Issue by cihadturhan** [matfish2/vue-tables-2#149] opened 2017-05-01 23:17 UTC
- Vue.js version: 2.2.6
- consumed using: browserify

It would be very nice to have a shortcut to add classes to columns. For example, I have a column displaying numbers:
```javascript
classes: {
   headingNumber: 'text-monospace text-right',
   //...
}
```

**Comment by matfish2** [comment] 2017-05-02 06:41
Duplicate of #111

**Closed by matfish2** 2017-05-02 06:41 UTC
Labels: duplicate
