### ISSUE TITLE
Passing variable as a prop for child component in templates not working

### ISSUE THREAD

**Issue by Chalkin** [matfish2/vue-tables-2#18] opened 2016-11-02 14:05 UTC
I'm trying to pass a variable from `row` through to my child-component but it's only rendering the plain text. When I try v-bind:url="row.avatar" or any other version (have tried many versions) it's not working either. I suspect the way you explain it in the docs (  url="row.something" ) is correct - but it's not working.

- Vue.js version: 2.0.3
- consumed using: webpack
- relevant code:

´´´javascript

Vue.component('avatar', {
    props: ['url', 'name'],
    template: `<div>{{url}}<img src="{{url}}" /></div>`
  })
....

templates: {
            name: function(h, row) {
              console.log(row.avatar);
              return '<avatar url="{row.avatar}" name="something"></avatar>'
            }
          },

´´´

This is only passing through the {row.avatar} as a plain string. So {{url}} is only rendering {row.avatar} despite the variable exists in row

**Comment by matfish2** [comment] 2016-11-02 15:54
Duplicate of #6. Use JSX, not HTML.

**Closed by matfish2** 2016-11-02 15:54 UTC
